export const APP_INIT = 'APP_INIT';
export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
export const SET_READING_STATUS = 'SET_READING_STATUS';

export const SHELF_INSERT = 'SHELF_INSERT';
export const SHELF_UPDATE = 'SHELF_UPDATE';

export const BOOK_UPDATE = 'BOOK_UPDATE';
export const BOOK_SEARCH_UPDATE = 'BOOK_SEARCH_UPDATE';
export const SET_HOME_SEARCH_STATUS = 'SET_HOME_SEARCH_STATUS';

export const WORD_SEARCH_UPDATE = 'WORD_SEARCH_UPDATE';
export const WORD_SEARCH_CLEAR = 'WORD_SEARCH_CLEAR';
export const WORD_UPDATE = 'WORD_UPDATE';
export const WORD_META_SET = 'WORD_META_SET';
export const WORD_META_PREPEND = 'WORD_META_PREPEND';
