# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeInit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeInit

  target 'ReactNativeInitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'React', :path => '../node_modules/react-native'
pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
