# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeInit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeInit

  target 'ReactNativeInitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'React', :path => '../node_modules/react-native'
pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'
